[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.4.4" }
selene = { github = "Kampfkarren/selene", version = "0.27.1" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.20.0" }
rbxcloud = { github = "Sleitnick/rbxcloud", version = "0.2.0" }